---
{{- $releaseNamespace := .Release.Namespace }}
{{- $fullName := include "kuard.fullname" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  namespace: {{ $releaseNamespace }}
  labels:
    {{- include "kuard.labels" . | nindent 4 }}
spec:
  # type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kuard.selectorLabels" . | nindent 4 }}
