{{- if .Values.serviceAccount.create -}}
---
{{- $releaseNamespace := .Release.Namespace }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kuard.serviceAccountName" . }}
  namespace: {{ $releaseNamespace }}
  labels:
    {{- include "kuard.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
