{{- if and .Values.ingress.enabled .Values.ingress.tls }}
  {{- $certType := pluck .Values.global.env .Values.ingress.certType | first | default .Values.ingress.certType._default }}
  {{- if eq $certType "letsencrypt-prod" }}
    {{- $email := pluck .Values.global.env .Values.ingress.acme.email | first | default .Values.ingress.acme.email._default }}
---
apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
kind: Issuer
metadata:
  name: {{ $certType }}
  namespace: {{ include "common.names.namespace" . | quote }}
  # namespace: kube-system
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: {{ $email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ $certType }}
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingress.ingressClassName }}
  {{- end }}
{{- end }}