{{- $releaseNamespace := .Release.Namespace }}
{{- $username := .Values.monitoring.username }}
{{- $password := .Values.monitoring.apiKey }}
{{- $usernameLog := .Values.log.username }}
{{- $passwordLog := .Values.log.apiKey }}
---
kind: ConfigMap
metadata:
  name: grafana-agent
  namespace: {{ $releaseNamespace}}
apiVersion: v1
data:
  agent.yaml: | 
    metrics:
      wal_directory: /var/lib/agent/wal
      global:
        scrape_interval: 60s
        external_labels:
          cluster: cloud
      configs:
      - name: integrations
        remote_write:
        - url: {{ .Values.prometheus.remoteWrite }}
          basic_auth:
            username: {{ $username }}
            password: {{ $password }}
        scrape_configs:
        - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          job_name: integrations/kubernetes/cadvisor
          kubernetes_sd_configs:
              - role: node
          metric_relabel_configs:
              - source_labels: [__name__]
                regex: kube_daemonset_status_number_misscheduled|kube_daemonset_status_number_available|container_fs_reads_bytes_total|cluster:namespace:pod_memory:active:kube_pod_container_resource_limits|container_network_receive_packets_dropped_total|kube_statefulset.*|container_network_transmit_bytes_total|kube_horizontalpodautoscaler_spec_max_replicas|node_namespace_pod_container:container_memory_cache|kube_pod_container_resource_limits|kubelet_pleg_relist_interval_seconds_bucket|container_cpu_cfs_throttled_periods_total|kube_statefulset_status_replicas_ready|kube_pod_container_info|container_fs_writes_total|node_namespace_pod_container:container_memory_swap|storage_operation_duration_seconds_count|cluster:namespace:pod_memory:active:kube_pod_container_resource_requests|kube_horizontalpodautoscaler_status_desired_replicas|container_network_receive_packets_total|namespace_memory:kube_pod_container_resource_limits:sum|kube_horizontalpodautoscaler_spec_min_replicas|kubelet_pod_worker_duration_seconds_count|kubelet_runtime_operations_errors_total|kube_statefulset_status_observed_generation|container_memory_working_set_bytes|kubelet_volume_stats_inodes|node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile|container_network_transmit_packets_total|kube_node_info|kube_statefulset_status_replicas_updated|kubelet_volume_stats_available_bytes|kube_statefulset_status_current_revision|node_namespace_pod_container:container_memory_working_set_bytes|process_resident_memory_bytes|cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits|kube_node_status_capacity|kube_job_failed|kube_pod_status_phase|kube_statefulset_status_replicas|kube_replicaset.*|namespace_memory:kube_pod_container_resource_requests:sum|node_namespace_pod_container:container_memory_rss|kubelet_pleg_relist_duration_seconds_count|up|kubelet_runtime_operations_total|process_cpu_seconds_total|kube_statefulset_status_update_revision|kubelet_server_expiration_renew_errors|kube_pod_start_time|kube_pod_info|kubelet_cgroup_manager_duration_seconds_count|kube_job_spec_completions|kubelet_volume_stats_inodes_used|cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests|kube_deployment_status_replicas_available|kube_deployment_metadata_generation|kube_namespace_status_phase|kubelet_running_container_count|namespace_cpu:kube_pod_container_resource_limits:sum|container_memory_cache|kube_deployment_spec_replicas|kubelet_certificate_manager_client_ttl_seconds|kube_pod_container_status_restarts_total|container_fs_reads_total|kubelet_running_pod_count|kubelet_running_pods|kube_daemonset.*|rest_client_requests_total|kube_statefulset_replicas|kubelet_certificate_manager_server_ttl_seconds|kubelet_running_containers|kubelet_node_config_error|kube_daemonset_status_desired_number_scheduled|kube_node_status_condition|container_fs_writes_bytes_total|container_memory_swap|kube_horizontalpodautoscaler_status_current_replicas|kubelet_certificate_manager_client_expiration_renew_errors|namespace_workload_pod|kube_pod_container_status_waiting_reason|kubelet_pleg_relist_duration_seconds_bucket|namespace_cpu:kube_pod_container_resource_requests:sum|storage_operation_errors_total|kube_deployment_status_observed_generation|kubernetes_build_info|kubelet_node_name|kube_job_status_succeeded|kube_pod_owner|kube_pod_container_resource_requests|kubelet_cgroup_manager_duration_seconds_bucket|kubelet_pod_start_duration_seconds_count|container_memory_rss|machine_memory_bytes|container_cpu_usage_seconds_total|node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate|kube_daemonset_status_current_number_scheduled|kubelet_pod_worker_duration_seconds_bucket|kube_deployment_status_replicas_updated|kube_daemonset_status_updated_number_scheduled|kube_job.*|container_network_transmit_packets_dropped_total|kubelet_volume_stats_capacity_bytes|namespace_workload_pod:kube_pod_owner:relabel|kube_resourcequota|volume_manager_total_volumes|go_goroutines|container_cpu_cfs_periods_total|kube_statefulset_metadata_generation|kube_node_status_allocatable|container_network_receive_bytes_total|kube_node_spec_taint|kube_replicaset_owner
                action: keep
          relabel_configs:
              - replacement: kubernetes.default.svc.cluster.local:443
                target_label: __address__
              - regex: (.+)
                replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
                source_labels:
                  - __meta_kubernetes_node_name
                target_label: __metrics_path__
          scheme: https
          tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: false
              server_name: kubernetes
        - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          job_name: integrations/kubernetes/kubelet
          kubernetes_sd_configs:
              - role: node
          metric_relabel_configs:
              - source_labels: [__name__]
                regex: kube_daemonset_status_number_misscheduled|kube_daemonset_status_number_available|container_fs_reads_bytes_total|cluster:namespace:pod_memory:active:kube_pod_container_resource_limits|container_network_receive_packets_dropped_total|kube_statefulset.*|container_network_transmit_bytes_total|kube_horizontalpodautoscaler_spec_max_replicas|node_namespace_pod_container:container_memory_cache|kube_pod_container_resource_limits|kubelet_pleg_relist_interval_seconds_bucket|container_cpu_cfs_throttled_periods_total|kube_statefulset_status_replicas_ready|kube_pod_container_info|container_fs_writes_total|node_namespace_pod_container:container_memory_swap|storage_operation_duration_seconds_count|cluster:namespace:pod_memory:active:kube_pod_container_resource_requests|kube_horizontalpodautoscaler_status_desired_replicas|container_network_receive_packets_total|namespace_memory:kube_pod_container_resource_limits:sum|kube_horizontalpodautoscaler_spec_min_replicas|kubelet_pod_worker_duration_seconds_count|kubelet_runtime_operations_errors_total|kube_statefulset_status_observed_generation|container_memory_working_set_bytes|kubelet_volume_stats_inodes|node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile|container_network_transmit_packets_total|kube_node_info|kube_statefulset_status_replicas_updated|kubelet_volume_stats_available_bytes|kube_statefulset_status_current_revision|node_namespace_pod_container:container_memory_working_set_bytes|process_resident_memory_bytes|cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits|kube_node_status_capacity|kube_job_failed|kube_pod_status_phase|kube_statefulset_status_replicas|kube_replicaset.*|namespace_memory:kube_pod_container_resource_requests:sum|node_namespace_pod_container:container_memory_rss|kubelet_pleg_relist_duration_seconds_count|up|kubelet_runtime_operations_total|process_cpu_seconds_total|kube_statefulset_status_update_revision|kubelet_server_expiration_renew_errors|kube_pod_start_time|kube_pod_info|kubelet_cgroup_manager_duration_seconds_count|kube_job_spec_completions|kubelet_volume_stats_inodes_used|cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests|kube_deployment_status_replicas_available|kube_deployment_metadata_generation|kube_namespace_status_phase|kubelet_running_container_count|namespace_cpu:kube_pod_container_resource_limits:sum|container_memory_cache|kube_deployment_spec_replicas|kubelet_certificate_manager_client_ttl_seconds|kube_pod_container_status_restarts_total|container_fs_reads_total|kubelet_running_pod_count|kubelet_running_pods|kube_daemonset.*|rest_client_requests_total|kube_statefulset_replicas|kubelet_certificate_manager_server_ttl_seconds|kubelet_running_containers|kubelet_node_config_error|kube_daemonset_status_desired_number_scheduled|kube_node_status_condition|container_fs_writes_bytes_total|container_memory_swap|kube_horizontalpodautoscaler_status_current_replicas|kubelet_certificate_manager_client_expiration_renew_errors|namespace_workload_pod|kube_pod_container_status_waiting_reason|kubelet_pleg_relist_duration_seconds_bucket|namespace_cpu:kube_pod_container_resource_requests:sum|storage_operation_errors_total|kube_deployment_status_observed_generation|kubernetes_build_info|kubelet_node_name|kube_job_status_succeeded|kube_pod_owner|kube_pod_container_resource_requests|kubelet_cgroup_manager_duration_seconds_bucket|kubelet_pod_start_duration_seconds_count|container_memory_rss|machine_memory_bytes|container_cpu_usage_seconds_total|node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate|kube_daemonset_status_current_number_scheduled|kubelet_pod_worker_duration_seconds_bucket|kube_deployment_status_replicas_updated|kube_daemonset_status_updated_number_scheduled|kube_job.*|container_network_transmit_packets_dropped_total|kubelet_volume_stats_capacity_bytes|namespace_workload_pod:kube_pod_owner:relabel|kube_resourcequota|volume_manager_total_volumes|go_goroutines|container_cpu_cfs_periods_total|kube_statefulset_metadata_generation|kube_node_status_allocatable|container_network_receive_bytes_total|kube_node_spec_taint|kube_replicaset_owner
                action: keep
          relabel_configs:
              - replacement: kubernetes.default.svc.cluster.local:443
                target_label: __address__
              - regex: (.+)
                replacement: /api/v1/nodes/${1}/proxy/metrics
                source_labels:
                  - __meta_kubernetes_node_name
                target_label: __metrics_path__
          scheme: https
          tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: false
              server_name: kubernetes
        {{- if .Values.node-exporter.enabled }}
        - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          job_name: integrations/node-exporter
          kubernetes_sd_configs:
            - role: pod
              namespaces:
                names:
                  - {{ $releaseNamespace }}
          relabel_configs:
            - action: keep
              regex: prometheus-node-exporter.*
              source_labels:
                - __meta_kubernetes_pod_label_app
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_node_name
              target_label: instance
            - action: replace
              source_labels:
                - __meta_kubernetes_namespace
              target_label: namespace
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: false
        {{- end }}
        - job_name: integrations/kubernetes/kube-state-metrics
          kubernetes_sd_configs:
              - role: pod
          metric_relabel_configs:
              - source_labels: [__name__]
                regex: kube_daemonset_status_number_misscheduled|kube_daemonset_status_number_available|container_fs_reads_bytes_total|cluster:namespace:pod_memory:active:kube_pod_container_resource_limits|container_network_receive_packets_dropped_total|kube_statefulset.*|container_network_transmit_bytes_total|kube_horizontalpodautoscaler_spec_max_replicas|node_namespace_pod_container:container_memory_cache|kube_pod_container_resource_limits|kubelet_pleg_relist_interval_seconds_bucket|container_cpu_cfs_throttled_periods_total|kube_statefulset_status_replicas_ready|kube_pod_container_info|container_fs_writes_total|node_namespace_pod_container:container_memory_swap|storage_operation_duration_seconds_count|cluster:namespace:pod_memory:active:kube_pod_container_resource_requests|kube_horizontalpodautoscaler_status_desired_replicas|container_network_receive_packets_total|namespace_memory:kube_pod_container_resource_limits:sum|kube_horizontalpodautoscaler_spec_min_replicas|kubelet_pod_worker_duration_seconds_count|kubelet_runtime_operations_errors_total|kube_statefulset_status_observed_generation|container_memory_working_set_bytes|kubelet_volume_stats_inodes|node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile|container_network_transmit_packets_total|kube_node_info|kube_statefulset_status_replicas_updated|kubelet_volume_stats_available_bytes|kube_statefulset_status_current_revision|node_namespace_pod_container:container_memory_working_set_bytes|process_resident_memory_bytes|cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits|kube_node_status_capacity|kube_job_failed|kube_pod_status_phase|kube_statefulset_status_replicas|kube_replicaset.*|namespace_memory:kube_pod_container_resource_requests:sum|node_namespace_pod_container:container_memory_rss|kubelet_pleg_relist_duration_seconds_count|up|kubelet_runtime_operations_total|process_cpu_seconds_total|kube_statefulset_status_update_revision|kubelet_server_expiration_renew_errors|kube_pod_start_time|kube_pod_info|kubelet_cgroup_manager_duration_seconds_count|kube_job_spec_completions|kubelet_volume_stats_inodes_used|cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests|kube_deployment_status_replicas_available|kube_deployment_metadata_generation|kube_namespace_status_phase|kubelet_running_container_count|namespace_cpu:kube_pod_container_resource_limits:sum|container_memory_cache|kube_deployment_spec_replicas|kubelet_certificate_manager_client_ttl_seconds|kube_pod_container_status_restarts_total|container_fs_reads_total|kubelet_running_pod_count|kubelet_running_pods|kube_daemonset.*|rest_client_requests_total|kube_statefulset_replicas|kubelet_certificate_manager_server_ttl_seconds|kubelet_running_containers|kubelet_node_config_error|kube_daemonset_status_desired_number_scheduled|kube_node_status_condition|container_fs_writes_bytes_total|container_memory_swap|kube_horizontalpodautoscaler_status_current_replicas|kubelet_certificate_manager_client_expiration_renew_errors|namespace_workload_pod|kube_pod_container_status_waiting_reason|kubelet_pleg_relist_duration_seconds_bucket|namespace_cpu:kube_pod_container_resource_requests:sum|storage_operation_errors_total|kube_deployment_status_observed_generation|kubernetes_build_info|kubelet_node_name|kube_job_status_succeeded|kube_pod_owner|kube_pod_container_resource_requests|kubelet_cgroup_manager_duration_seconds_bucket|kubelet_pod_start_duration_seconds_count|container_memory_rss|machine_memory_bytes|container_cpu_usage_seconds_total|node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate|kube_daemonset_status_current_number_scheduled|kubelet_pod_worker_duration_seconds_bucket|kube_deployment_status_replicas_updated|kube_daemonset_status_updated_number_scheduled|kube_job.*|container_network_transmit_packets_dropped_total|kubelet_volume_stats_capacity_bytes|namespace_workload_pod:kube_pod_owner:relabel|kube_resourcequota|volume_manager_total_volumes|go_goroutines|container_cpu_cfs_periods_total|kube_statefulset_metadata_generation|kube_node_status_allocatable|container_network_receive_bytes_total|kube_node_spec_taint|kube_replicaset_owner
                action: keep
          relabel_configs:
              - action: keep
                regex: kube-state-metrics
                source_labels:
                  - __meta_kubernetes_pod_label_app_kubernetes_io_name
        - job_name: cert-integration
          static_configs:
            - targets: ['cert-manager.cert-manager:9402']
        - job_name: "kubernetes-pods"
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            # Example relabel to scrape only pods that have
            # "example.io/should_be_scraped = true" annotation.
            #  - source_labels: [__meta_kubernetes_pod_annotation_example_io_should_be_scraped]
            #    action: keep
            #    regex: true
            #
            # Example relabel to customize metric path based on pod
            # "example.io/metric_path = <metric path>" annotation.
            #  - source_labels: [__meta_kubernetes_pod_annotation_example_io_metric_path]
            #    action: replace
            #    target_label: __metrics_path__
            #    regex: (.+)
            #
            # Example relabel to scrape only single, desired port for the pod
            # based on pod "example.io/scrape_port = <port>" annotation.
            #  - source_labels: [__address__, __meta_kubernetes_pod_annotation_example_io_scrape_port]
            #    action: replace
            #    regex: ([^:]+)(?::\d+)?;(\d+)
            #    replacement: $1:$2
            #    target_label: __address__
            # Expose Pod labels as metric labels
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            # Expose Pod namespace as metric namespace label
            - source_labels: [__meta_kubernetes_namespace]
              action: replace
              target_label: namespace
            # Expose Pod name as metric name label
            - source_labels: [__meta_kubernetes_pod_name]
              action: replace
              target_label: pod
        {{- with .Values.prometheus.extraScrapeConfigs }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    integrations:
      eventhandler:
        cache_path: /var/lib/agent/eventhandler.cache
        logs_instance: integrations
      # # https://grafana.com/docs/agent/latest/configuration/integrations/memcached-exporter-config/
      # memcached_exporter:
      #   enabled: true
      #   memcached_address: "memcached:11211"
    logs:
      configs:
      - name: integrations
        clients:
        - url: {{ .Values.log.remoteWrite }}
          basic_auth:
            username: {{ $usernameLog }}
            password: {{ $passwordLog }}
          external_labels:
            cluster: {{ .Values.clusterName }}
            job: integrations/kubernetes/eventhandler
        positions:
          filename: /tmp/positions.yaml
        target_config:
          sync_period: 10s