{{- if and .Values.log.enabled (eq .Values.log.collector "loki") }}
{{- $releaseNamespace := .Release.Namespace }}
{{- $username := .Values.monitoring.username }}
{{- $password := .Values.monitoring.apiKey }}
{{- $usernameLog := .Values.log.username }}
{{- $passwordLog := .Values.log.apiKey }}
---
kind: ConfigMap
metadata:
  name: grafana-agent-logs
  namespace: {{ $releaseNamespace}}
apiVersion: v1
data:
  agent.yaml: | 
{{- tpl (.Files.Get "conf/agent-loki.yaml") $ | indent 4 }}
{{- end }}