{{- $releaseNamespace := .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-agent
  namespace: {{ $releaseNamespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-agent-logs
  namespace: {{ $releaseNamespace }}
